ath_main_homepage:
    path:     /
    defaults: { _controller: AthMainBundle:Default:index }
ath_list_association:
    path:     /associations/list/{page}
    defaults: { _controller: AthMainBundle:Association:index, page: 1 }
ath_page_association:
    path:     /associations/{id}
    defaults: { _controller: AthMainBundle:Association:page }
    
ath_list_produit:
    path:     /produits/list/{page}
    defaults: { _controller: AthMainBundle:Produit:index, page: 1 }
ath_page_produit:
    path:     /produits/{id}
    defaults: { _controller: AthMainBundle:Produit:page }

ath_main_datavis_user:
    path: /admin/datavis/user
    defaults: { _controller: AthMainBundle:Datavisualisation:user }

ath_main_search_user:
    path:     /user/autocomplete
    defaults: { _controller: AthMainBundle:Default:searchUserAjax }

ath_main_follow_user:
    path:     /sportif/suivre/{slug}/{suivre}
    defaults: { _controller: AthMainBundle:Default:follow, suivre: 1 }

ath_main_user_settings:
    path:     /sportif/parametres
    defaults: { _controller: AthMainBundle:Default:userSettings }

ath_main_followers:
    path: /sportif/followers/{slug}
    defaults: { _controller: AthMainBundle:Default:followers }

ath_main_followers_ajax:
    path: /sportif/followers/ajax/{slug}
    defaults: { _controller: AthMainBundle:Default:followersAjax }

ath_main_event_sportifs:
    path: /sportif/evenements
    defaults: { _controller: AthMainBundle:Default:eventSportifs }

ath_main_event_sportifs_ajax:
    path: /sportif/evenements/ajax
    defaults: { _controller: AthMainBundle:Default:eventSportifsAjax }

ath_main_posts_ajax:
    path: /sportif/posts/ajax
    defaults: { _controller: AthMainBundle:Default:postsAjax }

ath_main_add_post:
    path: /sportif/add/post
    defaults: { _controller: AthMainBundle:Default:addPost }

ath_main_add_comment:
    path: /sportif/add/comment
    defaults: { _controller: AthMainBundle:Default:addCommentAjax }

ath_main_more_comments:
    path: /sportif/plus-commentaires
    defaults: { _controller: AthMainBundle:Default:moreCommentsAjax }

ath_main_share_post:
    path: /sportif/partager/article/{idPost}
    defaults: { _controller: AthMainBundle:Default:sharePost }

ath_main_remove_post:
    path: /sportif/supprimer/article
    defaults: { _controller: AthMainBundle:Default:removePostAjax }

ath_main_like_post:
    path: /sportif/aimer/article
    defaults: { _controller: AthMainBundle:Default:likePostAjax }

ath_main_add_comparateur:
    path: /sportif/ajouter/comparateur
    defaults: { _controller: AthMainBundle:Default:addComparateurAjax }
