<?php

namespace Ath\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupApplicationRepository extends EntityRepository
{
}
