<?php

namespace Ath\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * sportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportRepository extends EntityRepository
{
    public function getSportAll() {
        $query = $this
            ->createQueryBuilder('u')
            ->getQuery();

        return $query->getResult();
    }
}
