imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }


# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

parameters:
    locale: fr
    test.client.class: Ath\MainBundle\Tests\Client

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    globals:
        app_id_facebook: "%app_id_facebook%"
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/Resources/views/Ath/Admin": ath_admin_path
        "%kernel.root_dir%/Resources/views/Ath/Main": ath_main_path
        "%kernel.root_dir%/Resources/views/Ath/User": ath_user_path
        "%kernel.root_dir%/Resources/views": ath_views
    form:
        resources: [':Ath/Form:ath_form_page_theme.html.twig', 'SonataCoreBundle:Form:datepicker.html.twig']


# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default: 
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Ath\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type: Ath\UserBundle\Form\RegistrationType
            validation_groups: [AthRegistration]

        confirmation:
            enabled: true
    from_email:
        address:        "%email_from%"
        sender_name:    Athleteec

hwi_oauth:
    http_client:
        timeout:       10000
        verify_peer: false
        max_redirects: 1000
        ignore_errors: false

    firewall_name: main
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%app_id_facebook%"
            client_secret:       "%app_secret_facebook%"
            scope:               "email"
            infos_url:     "https://graph.facebook.com/me?fields=name,email,picture,birthday,gender,first_name,last_name"
            paths:
                email: email
            options:
                # display: popup
                csrf: true
        twitter:
            type: twitter
            client_id: "%app_id_twitter%"
            client_secret: "%app_secret_twitter%"
            scope: "email"
            paths:
                email: email
        google:
            type:                google
            client_id:           %app_id_google%
            client_secret:       %app_secret_google%
            scope:              "email"
            paths:
                email: email
            options:
                csrf: true

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_admin:
    title:                Athleteec
    # title_logo:           images/logo.png
    options:
        use_select2:    true # disable select2
        # Auto order groups and admins by label or id
        confirm_exit:         false
    templates:
        dashboard: :Ath:Admin/dashboard.html.twig
        layout: :Ath:Admin/standard_layout.html.twig
        user_block: :Ath:Admin/user_block.html.twig
        delete:   :Ath:Admin/delete.html.twig
    assets:
        stylesheets:
            # - compiled/front/common.css
            - sonata/atixheader/css/shared/bootstrap.css
            - sonata/atixheader/css/shared/bootstrap.responsive-table.css
            - sonata/atixheader/css/shared/sonata.atixSkin.css
            - sonata/atixformextra/css/farbtastic.css
            - sonata/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
            - sonata/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
            - cssAdmin/admin.css
            - sonata/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - sonata/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - sonata/sonataadmin/vendor/select2/select2.css
            - sonata/sonataadmin/vendor/select2/select2-bootstrap.css
            - sonata/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - sonata/sonataadmin/css/styles.css
            - sonata/sonataadmin/css/layout.css
            - sonata/atixformextra/css/farbtastic.css
        javascripts:
            # Defaults:
            - components/jquery/jquery.min.js
            - sonata/atixheader/js/atixResponsTable.js
            - sonata/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - sonata/sonatacore/vendor/moment/min/moment-with-locales.min.js
            - components/bootstrap/js/bootstrap.min.js
            - sonata/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            # - sonata/atixformextra/js/bootstrap-datetimepicker.js
            - sonata/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - sonata/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - sonata/sonataadmin/jquery/jquery.form.js
            - sonata/sonataadmin/jquery/jquery.confirmExit.js
            - sonata/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - sonata/sonataadmin/vendor/select2/select2.min.js
            - sonata/sonataadmin/App.js
            - sonata/sonataadmin/Admin.js
            - sonata/atixformextra/js/farbtastic.js
    security:
        handler: sonata.admin.security.handler.role

knp_paginator:
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig

services:
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
            - [ setDefaultLocale, [ %locale% ] ]
            - [ setTranslationFallback, [ false ] ]
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        micro:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        mini:
            quality: 75
            filters:
                thumbnail: { size: [70, 70], mode: outbound }
        small:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        medium:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
        profile:
            quality: 75
            filters:
                thumbnail: { size: [255, 255], mode: outbound }
        big:
            quality: 75
            filters:
                thumbnail: { size: [400, 400], mode: outbound }
ath_main:
    roles_gp_app:
        Utilisateur:
            ROLE_ADMIN_USER_LIST: Liste des utilisateurs
            ROLE_ADMIN_USER_VIEW: Voir un utilisateurs
            ROLE_ADMIN_USER_CREATE: Création d'un utilisateur
            ROLE_ADMIN_USER_EDIT: Modification d'un utilisateur
            ROLE_ADMIN_USER_DELETE: Supprimer un utilisateur
            ROLE_ADMIN_USER_EXPORT: Exporter un utilisateur
            ROLE_ADMIN_USER_PASSWORD: Modifier un mot de passe utilisateur
            ROLE_ADMIN_USER: Tous les droits utilisateurs
        Demande de celebrite:
            # ROLE_ADMIN_DEMANDE_CELEBRITE_LIST: Liste des demandes de célébrités
            # ROLE_ADMIN_DEMANDE_CELEBRITE_VIEW: Voir une demande de célébrité
            # ROLE_ADMIN_DEMANDE_CELEBRITE_DELETE: Supprimer une demande de célébrité
            # ROLE_ADMIN_DEMANDE_CELEBRITE_EXPORT: Exporter une demande de célébrité
            # ROLE_ADMIN_REPONSE_DEMANDE_CELEBRITE: Valider/refuser une demande de célébrité
            ROLE_ADMIN_DEMANDE_CELEBRITE: Valider/refuser une demande de célébrité
        Groupe:
            ROLE_ADMIN_GROUP_APPLICATION_LIST: Liste des groupes d'administration
            ROLE_ADMIN_GROUP_APPLICATION_VIEW: Voir un groupe d'administration
            ROLE_ADMIN_GROUP_APPLICATION_CREATE: Création d'un groupe d'administration
            ROLE_ADMIN_GROUP_APPLICATION_EDIT: Modification d'un groupe d'administration
            ROLE_ADMIN_GROUP_APPLICATION_DELETE: Supprimer un groupe d'administration
            ROLE_ADMIN_GROUP_APPLICATION_EXPORT: Exporter un groupe d'administration
            ROLE_ADMIN_GROUP_APPLICATION: Tous les droits groupes d'administration
        Categorie de produit:
            ROLE_ADMIN_CATEGORIE_PRODUIT_LIST: Liste des catégories de produits
            ROLE_ADMIN_CATEGORIE_PRODUIT_VIEW: Voir une catégorie de produit
            ROLE_ADMIN_CATEGORIE_PRODUIT_CREATE: Création d'une catégorie de produit
            ROLE_ADMIN_CATEGORIE_PRODUIT_EDIT: Modification d'une catégorie de produit
            ROLE_ADMIN_CATEGORIE_PRODUIT_DELETE: Supprimer une catégorie de produit
            ROLE_ADMIN_CATEGORIE_PRODUIT_EXPORT: Exporter une catégorie de produit
            ROLE_ADMIN_CATEGORIE_PRODUIT: Tous les droits catégorie de produit
        Produit:
            # ROLE_ADMIN_PRODUIT_LIST: Liste des produits
            # ROLE_ADMIN_PRODUIT_VIEW: Voir une catégorie de produit
            # ROLE_ADMIN_PRODUIT_CREATE: Création d'un produit
            # ROLE_ADMIN_PRODUIT_EDIT: Modification d'un produit
            # ROLE_ADMIN_PRODUIT_DELETE: Supprimer un produit
            # ROLE_ADMIN_PRODUIT_EXPORT: Exporter un produit
            ROLE_ADMIN_PRODUIT: Tous les droits produits
        Categorie de sport:
            ROLE_ADMIN_SPORT_LIST: Liste des catégorie de sports
            ROLE_ADMIN_SPORT_VIEW: Voir une catégorie de sport
            ROLE_ADMIN_SPORT_CREATE: Création d'une catégorie de sport
            ROLE_ADMIN_SPORT_EDIT: Modification d'une catégorie de sport
            ROLE_ADMIN_SPORT_DELETE: Supprimer une catégorie de sport
            ROLE_ADMIN_SPORT_EXPORT: Exporter une catégorie de sport
            ROLE_ADMIN_SPORT: Tous les droits catégorie de sport
        Discutions utilisateurs:
            ROLE_ADMIN_USER_DISCUSSION_LIST: Liste des discutions utilisateurs
            ROLE_ADMIN_USER_DISCUSSION_VIEW: Voir une discution utilisateurs
            ROLE_ADMIN_USER_DISCUSSION_CREATE: Création d'une discution utilisateurs
            ROLE_ADMIN_USER_DISCUSSION_EDIT: Modification d'une discution utilisateurs
            ROLE_ADMIN_USER_DISCUSSION_DELETE: Supprimer une discution utilisateurs
            ROLE_ADMIN_USER_DISCUSSION_EXPORT: Exporter une discution utilisateurs
            ROLE_ADMIN_USER_DISCUSSION: Tous les droits discutions utilisateurs
        Messages discutions:
            ROLE_ADMIN_MESSAGE_LIST: Liste des messages discutions
            ROLE_ADMIN_MESSAGE_VIEW: Voir un message
            ROLE_ADMIN_MESSAGE_CREATE: Création d'un message
            ROLE_ADMIN_MESSAGE_EDIT: Modification d'un message
            ROLE_ADMIN_MESSAGE_DELETE: Supprimer un message
            ROLE_ADMIN_MESSAGE_EXPORT: Exporter un message
            ROLE_ADMIN_MESSAGE: Tous les droits messages discutions
        Articles :
            ROLE_ADMIN_POST_LIST: Liste des articles
            ROLE_ADMIN_POST_VIEW: Voir un article
            ROLE_ADMIN_POST_CREATE: Création d'un article
            ROLE_ADMIN_POST_EDIT: Modification d'un article
            ROLE_ADMIN_POST_DELETE: Supprimer un article
            ROLE_ADMIN_POST_EXPORT: Exporter un article
            ROLE_ADMIN_POST: Tous les droits articles
        Commentaires:
            ROLE_ADMIN_COMMENT_LIST: Liste des commentaires
            ROLE_ADMIN_COMMENT_VIEW: Voir un commentaire
            ROLE_ADMIN_COMMENT_CREATE: Création d'un commentaire
            ROLE_ADMIN_COMMENT_EDIT: Modification d'un commentaire
            ROLE_ADMIN_COMMENT_DELETE: Supprimer un commentaire
            ROLE_ADMIN_COMMENT_EXPORT: Exporter un commentaire
            ROLE_ADMIN_COMMENT: Tous les droits commentaires
        Evenements sportifs:
            ROLE_ADMIN_EVENT_ADMIN_LIST: Liste des évènements sportifs
            ROLE_ADMIN_EVENT_ADMIN_VIEW: Voir un évènement sportif
            ROLE_ADMIN_EVENT_ADMIN_CREATE: Créer un évènement sportif
            ROLE_ADMIN_EVENT_ADMIN_EDIT: Modification d'un évènement sportif
            ROLE_ADMIN_EVENT_ADMIN_DELETE: Supprimer un évènement sportif
            ROLE_ADMIN_EVENT_ADMIN_EXPORT: Exporter un évènement sportif
            ROLE_ADMIN_EVENT_ADMIN: Tous les droits évènements sportifs