imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    globals:
        app_id_facebook: "%app_id_facebook%"
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/Resources/views/Ath/Admin": ath_admin_path
        "%kernel.root_dir%/Resources/views/Ath/Main": ath_main_path
        "%kernel.root_dir%/Resources/views/Ath/User": ath_user_path
        "%kernel.root_dir%/Resources/views": ath_views
    form:
        resources: [':Ath/Form:ath_form_page_theme.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Ath\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type: Ath\UserBundle\Form\RegistrationType
            validation_groups: [AthRegistration]

        confirmation:
            enabled: true
    from_email:
        address:        "%email_from%"
        sender_name:    Athleteec

hwi_oauth:
    http_client:
        timeout:       10000
        verify_peer: false
        max_redirects: 1000
        ignore_errors: false

    firewall_name: main
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%app_id_facebook%"
            client_secret:       "%app_secret_facebook%"
            scope:               "email"
            infos_url:     "https://graph.facebook.com/me?fields=name,email,picture,birthday,gender,first_name,last_name"
            paths:
                email: email
            options:
                # display: popup
                csrf: true
        twitter:
            type: twitter
            client_id: "%app_id_twitter%"
            client_secret: "%app_secret_twitter%"
            scope: "email"
            paths:
                email: email
        google:
            type:                google
            client_id:           %app_id_google%
            client_secret:       %app_secret_google%
            scope:              "email"
            paths:
                email: email
            options:
                csrf: true

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_admin:
    title:                Athleteec
    # title_logo:           images/logo.png
    options:
        # Auto order groups and admins by label or id
        confirm_exit:         false
    templates:
        dashboard: :Ath:Admin/dashboard.html.twig
        layout: :Ath:Admin/standard_layout.html.twig
        user_block: :Ath:Admin/user_block.html.twig
        delete:   :Ath:Admin/delete.html.twig
    assets:
        stylesheets:
            # - compiled/front/common.css
            - bundles/atixheader/css/shared/bootstrap.css
            - bundles/atixheader/css/shared/bootstrap.responsive-table.css
            - bundles/atixheader/css/shared/sonata.atixSkin.css
            - bundles/atixformextra/css/farbtastic.css
            - bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
            - cssAdmin/admin.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonataadmin/vendor/select2/select2.css
            - bundles/sonataadmin/vendor/select2/select2-bootstrap.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/atixformextra/css/farbtastic.css
        javascripts:
            # Defaults:
            - components/jquery/jquery.min.js
            - bundles/atixheader/js/atixResponsTable.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment-with-locales.min.js
            - components/bootstrap/js/bootstrap.min.js
            - bundles/atixformextra/js/bootstrap-datetimepicker.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonataadmin/vendor/select2/select2.min.js
            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js
            - bundles/atixformextra/js/farbtastic.js

knp_paginator:
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig

services:
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
            - [ setDefaultLocale, [ %locale% ] ]
            - [ setTranslationFallback, [ false ] ]
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

avalanche_imagine:
    web_root: %kernel.root_dir%/../web
    cache_prefix: uploads/avalanche/
    filters:
        user_detail:
            type:    thumbnail
            options: { size: [124, 124], mode: outbound, quality: 100, format: png }
        user:
            type:    thumbnail
            options: { size: [96, 96], mode: outbound, quality: 100, format: png }
        user_short:
            type:    thumbnail
            options: { size: [48, 48], mode: outbound, quality: 100, format: png }
        user_mini:
            type:    thumbnail
            options: { size: [32, 32], mode: outbound, quality: 100, format: png }
        user_micro:
            type:    thumbnail
            options: { size: [24, 24], mode: outbound, quality: 100, format: png }