security:
    role_hierarchy:
        ROLE_ADMIN_TABORD:
        # Admin User
        ROLE_ADMIN_USER_LIST: [ROLE_ADMIN_TABORD, ROLE_USER]
        ROLE_ADMIN_USER_VIEW: ROLE_ADMIN_USER_LIST
        ROLE_ADMIN_USER_CREATE: ROLE_ADMIN_USER_VIEW
        ROLE_ADMIN_USER_EDIT: ROLE_ADMIN_USER_VIEW
        ROLE_ADMIN_USER_DELETE: ROLE_ADMIN_USER_VIEW
        ROLE_ADMIN_USER_EXPORT: ROLE_ADMIN_USER_VIEW
        ROLE_ADMIN_USER_PASSWORD: ROLE_ADMIN_USER_VIEW
        ROLE_ADMIN_USER: [ROLE_ADMIN_USER_EXPORT, ROLE_ADMIN_USER_DELETE, ROLE_ADMIN_USER_EDIT, ROLE_ADMIN_USER_CREATE, ROLE_ADMIN_USER_PASSWORD]
        
        # Admin DEMANDE_CELEBRITE
        ROLE_ADMIN_DEMANDE_CELEBRITE_LIST: [ROLE_ADMIN_TABORD, ROLE_USER]
        ROLE_ADMIN_DEMANDE_CELEBRITE_VIEW: ROLE_ADMIN_DEMANDE_CELEBRITE_LIST
        # ROLE_ADMIN_DEMANDE_CELEBRITE_CREATE: ROLE_ADMIN_DEMANDE_CELEBRITE_VIEW
        # ROLE_ADMIN_DEMANDE_CELEBRITE_EDIT: ROLE_ADMIN_DEMANDE_CELEBRITE_VIEW
        ROLE_ADMIN_DEMANDE_CELEBRITE_DELETE: ROLE_ADMIN_DEMANDE_CELEBRITE_VIEW
        ROLE_ADMIN_DEMANDE_CELEBRITE_EXPORT: ROLE_ADMIN_DEMANDE_CELEBRITE_VIEW
        ROLE_ADMIN_REPONSE_DEMANDE_CELEBRITE: ROLE_ADMIN_DEMANDE_CELEBRITE_VIEW
        ROLE_ADMIN_DEMANDE_CELEBRITE: [ROLE_ADMIN_DEMANDE_CELEBRITE_EXPORT, ROLE_ADMIN_DEMANDE_CELEBRITE_DELETE, ROLE_ADMIN_DEMANDE_CELEBRITE_EDIT, ROLE_ADMIN_DEMANDE_CELEBRITE_CREATE, ROLE_ADMIN_REPONSE_DEMANDE_CELEBRITE]
        
        # Admin Group
        ROLE_ADMIN_GROUP_APPLICATION_LIST: [ROLE_ADMIN_TABORD, ROLE_USER]
        ROLE_ADMIN_GROUP_APPLICATION_VIEW: ROLE_ADMIN_GROUP_APPLICATION_LIST
        ROLE_ADMIN_GROUP_APPLICATION_CREATE: ROLE_ADMIN_GROUP_APPLICATION_VIEW
        ROLE_ADMIN_GROUP_APPLICATION_EDIT: ROLE_ADMIN_GROUP_APPLICATION_VIEW
        ROLE_ADMIN_GROUP_APPLICATION_DELETE: ROLE_ADMIN_GROUP_APPLICATION_VIEW
        ROLE_ADMIN_GROUP_APPLICATION_EXPORT: ROLE_ADMIN_GROUP_APPLICATION_VIEW
        ROLE_ADMIN_GROUP_APPLICATION: [ROLE_ADMIN_GROUP_APPLICATION_EXPORT, ROLE_ADMIN_GROUP_APPLICATION_DELETE, ROLE_ADMIN_GROUP_APPLICATION_EDIT, ROLE_ADMIN_GROUP_APPLICATION_CREATE]

        # Admin CategorieProduit
        ROLE_ADMIN_CATEGORIE_PRODUIT_LIST: [ROLE_ADMIN_TABORD, ROLE_USER]
        ROLE_ADMIN_CATEGORIE_PRODUIT_VIEW: ROLE_ADMIN_CATEGORIE_PRODUIT_LIST
        ROLE_ADMIN_CATEGORIE_PRODUIT_CREATE: ROLE_ADMIN_CATEGORIE_PRODUIT_VIEW
        ROLE_ADMIN_CATEGORIE_PRODUIT_EDIT: ROLE_ADMIN_CATEGORIE_PRODUIT_VIEW
        ROLE_ADMIN_CATEGORIE_PRODUIT_DELETE: ROLE_ADMIN_CATEGORIE_PRODUIT_VIEW
        ROLE_ADMIN_CATEGORIE_PRODUIT_EXPORT: ROLE_ADMIN_CATEGORIE_PRODUIT_VIEW
        ROLE_ADMIN_CATEGORIE_PRODUIT: [ROLE_ADMIN_CATEGORIE_PRODUIT_EXPORT, ROLE_ADMIN_CATEGORIE_PRODUIT_DELETE, ROLE_ADMIN_CATEGORIE_PRODUIT_EDIT, ROLE_ADMIN_CATEGORIE_PRODUIT_CREATE]
    
        # Admin Produit
        ROLE_ADMIN_PRODUIT_LIST: [ROLE_ADMIN_TABORD, ROLE_USER]
        ROLE_ADMIN_PRODUIT_VIEW: ROLE_ADMIN_PRODUIT_LIST
        ROLE_ADMIN_PRODUIT_CREATE: ROLE_ADMIN_PRODUIT_VIEW
        ROLE_ADMIN_PRODUIT_EDIT: ROLE_ADMIN_PRODUIT_VIEW
        ROLE_ADMIN_PRODUIT_DELETE: ROLE_ADMIN_PRODUIT_VIEW
        ROLE_ADMIN_PRODUIT_EXPORT: ROLE_ADMIN_PRODUIT_VIEW
        ROLE_ADMIN_PRODUIT: [ROLE_ADMIN_PRODUIT_EXPORT, ROLE_ADMIN_PRODUIT_DELETE, ROLE_ADMIN_PRODUIT_EDIT, ROLE_ADMIN_PRODUIT_CREATE]
        
        # Admin Sport
        ROLE_ADMIN_SPORT_LIST: [ROLE_ADMIN_TABORD, ROLE_USER]
        ROLE_ADMIN_SPORT_VIEW: ROLE_ADMIN_SPORT_LIST
        ROLE_ADMIN_SPORT_CREATE: ROLE_ADMIN_SPORT_VIEW
        ROLE_ADMIN_SPORT_EDIT: ROLE_ADMIN_SPORT_VIEW
        ROLE_ADMIN_SPORT_DELETE: ROLE_ADMIN_SPORT_VIEW
        ROLE_ADMIN_SPORT_EXPORT: ROLE_ADMIN_SPORT_VIEW
        ROLE_ADMIN_SPORT: [ROLE_ADMIN_SPORT_EXPORT, ROLE_ADMIN_SPORT_DELETE, ROLE_ADMIN_SPORT_EDIT, ROLE_ADMIN_SPORT_CREATE]

        # Admin UserDiscussion
        ROLE_ADMIN_USER_DISCUSSION_LIST: [ROLE_ADMIN_TABORD, ROLE_USER]
        ROLE_ADMIN_USER_DISCUSSION_VIEW: ROLE_ADMIN_USER_DISCUSSION_LIST
        ROLE_ADMIN_USER_DISCUSSION_CREATE: ROLE_ADMIN_USER_DISCUSSION_VIEW
        ROLE_ADMIN_USER_DISCUSSION_EDIT: ROLE_ADMIN_USER_DISCUSSION_VIEW
        ROLE_ADMIN_USER_DISCUSSION_DELETE: ROLE_ADMIN_USER_DISCUSSION_VIEW
        ROLE_ADMIN_USER_DISCUSSION_EXPORT: ROLE_ADMIN_USER_DISCUSSION_VIEW
        ROLE_ADMIN_USER_DISCUSSION: [ROLE_ADMIN_USER_DISCUSSION_EXPORT, ROLE_ADMIN_USER_DISCUSSION_DELETE, ROLE_ADMIN_USER_DISCUSSION_EDIT, ROLE_ADMIN_USER_DISCUSSION_CREATE]
        
        # Admin Message
        ROLE_ADMIN_MESSAGE_LIST: [ROLE_ADMIN_TABORD, ROLE_USER]
        ROLE_ADMIN_MESSAGE_VIEW: ROLE_ADMIN_MESSAGE_LIST
        ROLE_ADMIN_MESSAGE_CREATE: ROLE_ADMIN_MESSAGE_VIEW
        ROLE_ADMIN_MESSAGE_EDIT: ROLE_ADMIN_MESSAGE_VIEW
        ROLE_ADMIN_MESSAGE_DELETE: ROLE_ADMIN_MESSAGE_VIEW
        ROLE_ADMIN_MESSAGE_EXPORT: ROLE_ADMIN_MESSAGE_VIEW
        ROLE_ADMIN_MESSAGE: [ROLE_ADMIN_MESSAGE_EXPORT, ROLE_ADMIN_MESSAGE_DELETE, ROLE_ADMIN_MESSAGE_EDIT, ROLE_ADMIN_MESSAGE_CREATE]
        
        # Admin Post
        ROLE_ADMIN_POST_LIST: [ROLE_ADMIN_TABORD, ROLE_USER]
        ROLE_ADMIN_POST_VIEW: ROLE_ADMIN_POST_LIST
        ROLE_ADMIN_POST_CREATE: ROLE_ADMIN_POST_VIEW
        ROLE_ADMIN_POST_EDIT: ROLE_ADMIN_POST_VIEW
        ROLE_ADMIN_POST_DELETE: ROLE_ADMIN_POST_VIEW
        ROLE_ADMIN_POST_EXPORT: ROLE_ADMIN_POST_VIEW
        ROLE_ADMIN_POST: [ROLE_ADMIN_POST_EXPORT, ROLE_ADMIN_POST_DELETE, ROLE_ADMIN_POST_EDIT, ROLE_ADMIN_POST_CREATE]
        
        # Admin COMMENT
        ROLE_ADMIN_COMMENT_LIST: [ROLE_ADMIN_TABORD, ROLE_USER]
        ROLE_ADMIN_COMMENT_VIEW: ROLE_ADMIN_COMMENT_LIST
        ROLE_ADMIN_COMMENT_CREATE: ROLE_ADMIN_COMMENT_VIEW
        ROLE_ADMIN_COMMENT_EDIT: ROLE_ADMIN_COMMENT_VIEW
        ROLE_ADMIN_COMMENT_DELETE: ROLE_ADMIN_COMMENT_VIEW
        ROLE_ADMIN_COMMENT_EXPORT: ROLE_ADMIN_COMMENT_VIEW
        ROLE_ADMIN_COMMENT: [ROLE_ADMIN_COMMENT_EXPORT, ROLE_ADMIN_COMMENT_DELETE, ROLE_ADMIN_COMMENT_EDIT, ROLE_ADMIN_COMMENT_CREATE]

        # Admin Event admin
        ROLE_ADMIN_EVENT_ADMIN_LIST: [ROLE_ADMIN_TABORD, ROLE_USER]
        ROLE_ADMIN_EVENT_ADMIN_VIEW: ROLE_ADMIN_EVENT_ADMIN_LIST
        ROLE_ADMIN_EVENT_ADMIN_CREATE: ROLE_ADMIN_EVENT_ADMIN_VIEW
        ROLE_ADMIN_EVENT_ADMIN_EDIT: ROLE_ADMIN_EVENT_ADMIN_VIEW
        ROLE_ADMIN_EVENT_ADMIN_DELETE: ROLE_ADMIN_EVENT_ADMIN_VIEW
        ROLE_ADMIN_EVENT_ADMIN_EXPORT: ROLE_ADMIN_EVENT_ADMIN_VIEW
        ROLE_ADMIN_EVENT_ADMIN: [ROLE_ADMIN_EVENT_ADMIN_EXPORT, ROLE_ADMIN_EVENT_ADMIN_DELETE, ROLE_ADMIN_EVENT_ADMIN_EDIT, ROLE_ADMIN_EVENT_ADMIN_CREATE]

        ROLE_ASSOC: ROLE_USER
        ROLE_CELEBRITE: ROLE_USER
        ROLE_ADMIN:       [ROLE_ASSOC, ROLE_CELEBRITE, ROLE_ADMIN_USER, ROLE_ADMIN_DEMANDE_CELEBRITE, ROLE_ADMIN_GROUP_APPLICATION, ROLE_ADMIN_CATEGORIE_PRODUIT, ROLE_ADMIN_PRODUIT, ROLE_ADMIN_SPORT, ROLE_ADMIN_USER_DISCUSSION, ROLE_ADMIN_MESSAGE, ROLE_ADMIN_POST, ROLE_ADMIN_COMMENT, ROLE_ADMIN_EVENT_ADMIN, ROLE_ALLOWED_TO_SWITCH]
