ath_main:
    resource: "@AthMainBundle/Resources/config/routing.yml"
    prefix:   /

ath_user:
    resource: "@AthUserBundle/Resources/config/routing.yml"
    prefix:   /
    
_imagine:
    resource: .
    type:     imagine