ath_main:
    resource: "@AthMainBundle/Resources/config/routing.yml"
    prefix:   /

ath_user:
    resource: "@AthUserBundle/Resources/config/routing.yml"
    prefix:   /
    
# _imagine:
#     resource: .
#     type:     imagine
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#HWIOAuthBundle routes
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

# hwi_oauth_connect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#     prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
facebook_login:
    pattern: /login/check-facebook
 
google_login:
    pattern: /login/check-google
    
twitter_login:
    pattern: /login/check-twitter

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin