ath_user_homepage:
    path:     /
    defaults: { _controller: AthUserBundle:Default:index }

# fOSUser routes
fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
   resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
   prefix: /profile

fos_user_register:
   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
   prefix: /register

fos_user_resetting:
   resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
   prefix: /resetting

fos_user_change_password:
   resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
   prefix: /profile

user_security_login:
    pattern:    /login
    defaults:   { _controller: AthUserBundle:Security:login }

user_security_logout:
    pattern:    /logout
    defaults:   { _controller: AthUserBundle:Security:logout }

user_security_check:
    pattern:    /login_check
    defaults:   { _controller: AthUserBundle:Security:check }

user_security_check_type:
    pattern:    /login_check_type
    defaults:   { _controller: AthUserBundle:Security:checkTest }