ath_user_homepage:
    path:     /
    defaults: { _controller: AthUserBundle:Default:index }

ath_user_remove_photo:
    path: /user/remove-my-photo
    defaults: { _controller: AthUserBundle:Profile:removePhoto }

ath_user_demande_celebrite:
    path: /user/demande-celebrite
    defaults: { _controller: AthUserBundle:Profile:demandeCelebrite }

# fOSUser routes
fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
   resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
   prefix: /profile

fos_user_register:
   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
   prefix: /register

fos_user_resetting:
   resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
   prefix: /resetting

fos_user_change_password:
   resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
   prefix: /profile

fos_user_profile_edit:
    pattern: /modifier/profil
    defaults: { _controller: AthUserBundle:Profile:edit }
    requirements:
        _method: GET|POST

fos_user_resetting_request:
    pattern: /resetting/request
    defaults: { _controller: 'AthUserBundle:Resetting:request' }
    requirements:
        method: "GET"

fos_user_resetting_send_email:
    pattern: /resetting/send-email
    defaults: { _controller: 'AthUserBundle:Resetting:sendEmail' }
    requirements:
        method: "POST"

fos_user_resetting_check_email:
    pattern: /resetting/check-email
    defaults: { _controller: 'AthUserBundle:Resetting:checkEmail' }
    requirements:
        method: "GET"

fos_user_resetting_reset:
    pattern: /resetting/reset/{token}
    defaults: { _controller: 'AthUserBundle:Resetting:reset' }
    requirements:
        method: "GET|POST"

### UserBundle -> Fos user route override
ath_user_change_password:
    pattern: /profile/change-password
    defaults: { _controller: 'AthUserBundle:ChangePassword:changePassword' }

user_security_login:
    pattern:    /login
    defaults:   { _controller: AthUserBundle:Security:login }

user_security_logout:
    pattern:    /logout
    defaults:   { _controller: AthUserBundle:Security:logout }

user_security_check:
    pattern:    /login_check
    defaults:   { _controller: AthUserBundle:Security:check }

user_security_check_type:
    pattern:    /login_check_type
    defaults:   { _controller: AthUserBundle:Security:checkTest }

# Permet de changer le parametre langue dans la configuration du site
ath_choose_langue:
    pattern: /public/choisir-langue/{langue}
    defaults: { _controller: 'AthUserBundle:Default:choisirLangue' }
    requirements:
        langue: en|fr

