services:
    # se déclenche lors de la connexion
    ath_user.login_success_handler:
        class: Ath\UserBundle\Managers\LoginSuccessHandler
        arguments:  [@router, @security.context, @session]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    
    my_user_provider:
        class: Ath\UserBundle\Security\Core\User\MyOAuthProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebookId, google: googleId}, @doctrine.orm.default_entity_manager, '@service_container']

    # Fosuser registration override
    ath.form.registration:
        class: Ath\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    
    ath.locale_listener:
        class: Ath\UserBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
    
    ath.user.validator.post_registration_validation:
        class: Ath\UserBundle\Validator\Constraints\ConditionalValidatorForUser
        tags:
            - { name: validator.constraint_validator, alias: post_registration_validation }

    ath.user.form.handler.edit_profile:
        class: Ath\UserBundle\Form\Handler\EditProfileFormHandler
        scope: request
        arguments:
          - "@request"
          - "@doctrine.orm.default_entity_manager"
          - "@session"
          - "@translator"
        tags:
            - { name: form.handler, alias: edit_profile.handler }
