services:
    # se déclenche lors de la connexion
    ath_user.login_success_handler:
        class: Ath\UserBundle\Managers\LoginSuccessHandler
        arguments:  [@router, @security.context, @session]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
            
    # Fosuser registration override
    ath.form.registration:
        class: Ath\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    
    ath.locale_listener:
        class: Ath\UserBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
    