<?php

namespace Ath\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAssociationAll() {
        $query = $this
            ->createQueryBuilder('u')
            ->where('u.statutJuridique = :statutJuridique')
            ->setParameter('statutJuridique', 2)
            ->getQuery();

        return $query->getResult();
    }

    /**
     * getUserActivesAutocomplete
     * @param  string $string
     * @return array of collection of this
     */
    public function getUserActivesAutocomplete($string){
		$query = $this->createQueryBuilder('u')
	    	->where('u.enabled = :enabled')
	    	->andWhere('u.nom like :string')
            ->orderBy('u.nom', 'DESC')
	    	->setParameters(array(
	    		'enabled' => 1,
	    		'string' => '%'. $string .'%'
	    	))
	    	->getQuery()
	    	->getResult();

		return $query;
	}

    /**
     * getFollowers => retourne les users qui me suivent
     * 
     * @param  User $userDestinataire
     * @return array of collection of this
     */
    public function getFollowers($userDestinataire){
        $query = $this->createQueryBuilder('u')
            ->Join('u.userEmetteursFollow', 'uef')
            ->where('uef.userDestinataire = :userDestinataire')
            ->andWhere('uef.accepte = :accepte')
            ->orderBy('u.nom', 'DESC')
            ->setParameters(array(
                'userDestinataire' => $userDestinataire,
                'accepte' => 1
            ))
            ->getQuery()
            ->getResult();

        return $query;
    }

    /**
     * getAmiFollows => retourne les personnes que je suis
     * 
     * @param  User $userEmetteur
     * @return array of collection of this
     */
    public function getAmiFollows($userEmetteur){
        $query = $this->createQueryBuilder('u')
            ->Join('u.userDestinatairesFollow', 'udf')
            ->where('udf.userEmetteur = :userEmetteur')
            ->andWhere('udf.accepte = :accepte')
            ->orderBy('u.nom', 'DESC')
            ->setParameters(array(
                'userEmetteur' => $userEmetteur,
                'accepte' => 1
            ))
            ->getQuery()
            ->getResult();

        return $query;
    }

}
