<?php

namespace Ath\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAssociationAll() {
        $query = $this
            ->createQueryBuilder('u')
            ->where('u.statutJuridique = :statutJuridique')
            ->setParameter('statutJuridique', 2)
            ->getQuery();

        return $query->getResult();
    }

    /**
     * getUserActivesAutocomplete
     * @param  string $string
     * @return array of collection of this
     */
    public function getUserActivesAutocomplete($string){
		$query = $this->createQueryBuilder('u')
	    	->where('u.enabled = :enabled')
	    	->andWhere('u.nom like :string')
	    	->setParameters(array(
	    		'enabled' => 1,
	    		'string' => '%'. $string .'%'
	    	))
	    	->getQuery()
	    	->getResult();

		return $query;
	}
}
